name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Java files
        run: javac -d out $(find . -name "*.java")

      - name: Run All Java Programs
        run: |
          for class in $(find out -name "*.class" | sed 's|out/||' | sed 's|.class||' | tr '/' '.'); do
            echo "Running $class..."
            java -cp out $class || echo "Skipping $class due to error."
          done
